# Generated by Django 5.2.8 on 2025-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="featured_prodcut",
            new_name="featured_product",
        ),
    ]
