# Generated by Django 5.2.8 on 2025-11-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_rename_featured_prodcut_category_featured_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="featured_product",
            new_name="featured_expenditure",
        ),
    ]
